default: &default
  adapter: <%= ENV['DB_ADAPTER'] || 'mysql2' %>
  encoding: <%= ENV['DB_ADAPTER'] || 'utf8mb4' %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>

development:
  <<: *default
  database: <%= ENV['DATABASE_DATABASE'] || 'silvermon_dev' %>

test:
  <<: *default
  database: <%= ENV['DATABASE_DATABASE'] || 'silvermon_test' %>

production:
  <<: *default
  database: <%= ENV['DATABASE_DATABASE'] || 'silvermon_prd' %>
